#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 ws3 

bspc config border_width        1 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a st desktop='^2' state=floating follow=on
bspc rule -a librewolf-bin desktop='^1'

bspc config focus_follows_pointer true

# Border Colors 
wal -i /home/kizzy/Pictures/Wallpapers/Spac.png &
. "/home/kizzy/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"


#Autostart Programs
feh --bg-scale ~/Pictures/Wallpapers/Spac.png
polybar
killall polybar && polybar

